source 'https://rubygems.org'

ruby '2.7.1'
gem "nokogiri", '1.10.10'
gem 'rspec', '3.9'
gem 'rubocop', '0.92.0'
gem 'simplecov'
gem 'open-uri'
gem 'histogram'
gem 'ascii-charts'
gem 'spreadsheets', '1.2.6'
gem 'csv', '3.1.7'
