source 'https://rubygems.org'

ruby '2.7.1'
gem 'ascii-charts'
gem 'histogram'
gem 'nokogiri', '1.10.10'
gem 'open-uri'
gem 'rspec', '3.9'
gem 'rubocop', '0.92.0'
gem 'simplecov'
gem 'spreadsheet', '1.2.6'
